<?php 
/*
* Filename: about.php
* About page. Nothing fancy.
*
*/

require_once('includes/config.php'); 
require_once('templates/header.php');
?>
		<div class="content ninecol about">
			<h2>What is Phillipian Pulse?</h2>
			<p class="bigger">Phillipian Pulse is your <b>go-to</b> place for <b>campus information</b>.</p>
			<p>Pulse content is meant to be <b>bite-sized</b> so you can quickly learn about campus happenings. It serves as a constant feed of news, ideas, and media generated by the Phillips Academy community as well as an ongoing <b>dialogue</b> between the members of our school.</p>
			<p>We're looking for <b>you</b> to submit to the Pulse. All the content here is generated by the community: we're looking for short reports, reflections, photos, announcements, and videos.</p>
			<p>The Pulse also aggregates data from various sources such as Twitter feeds from the Phillipian to keep you updated.</p>
			<p>Wanna get started?  Click “Add to the Pulse” in the right sidebar and <b>change how information is communicated on campus</b>.</p>
			<p>Are you a club? Register your club to post club details to the Pulse by emailing eouyang.</p>
			<p>Are you an alumni? Want to reach to the PA community? Send your message in.</p>
		</div>
		<div class="threecol sidebar last">
			<div class="twitter-sources">
				<h4>We're including</h4>
					<ul>
						<li><a href="http://twitter.com/the_phillipian">@the_phillipian</a></li>
						<li><a href="http://twitter.com/the_phillipian">@PhillipianNews</a></li>
						<li><a href="http://twitter.com/the_phillipian">@PhillipianOpEd</a></li>
						<li><a href="http://twitter.com/the_phillipian">@PhillipianArts</a></li>
						<li><a href="http://twitter.com/the_phillipian">@PhillipianSprts</a></li>
						<li><a href="http://twitter.com/the_phillipian">@PhillipianFeech</a></li>
						<li>Andover Pulse</li>
						<li>Phillipian Pulse</li>
						<li>Clubs Pulse</li>
						<li>Alumni Pulse</li>
					</ul>			
			</div>
			<a class="rounded add-link" href="http://www.tumblr.com/submit_form/<?php echo $main_tumblr_url ?>">Add to the Pulse</a>
			<p>Want your feed to get added? Send a message to eouyang.</p>
		</div>
<?php require_once('templates/footer.php'); ?>

